### ISSUE TITLE
instabot to be updated to 0.5.10

### ISSUE THREAD

**Issue by Zzo911** [feedsbrain/instabot-docker#10]
Hi,

The docker container stops with the following message.

Starting instabot for username: myaccount
Session file: /app/session/myaccount.session
Newer version available: 0.5.10, The current version: 0.5.9
To update, please type
python3 -m pip install instabot-py --upgrade --no-cache-dir 
 > You can ignore warning, run the instabot with --ignore-updates flag

Regards

**Comment by feedsbrain** [comment]
Instabot is updated to 0.5.12
